
- name: Log into DockerHub
  command: docker login -u "{{docker_username}}" -p "{{docker_password}}"

- name: ensure srv directory
  action: file dest=/srv state=directory

- name: set permissions on /srv directory
  action: file path=/srv mode=u=rwX,g=rwX,o=X recurse=yes owner=ubuntu
  become_user: root

- name: Ensure docker-compose file is up to date
  action: template src=/Users/maxfowler/computer/projects/opensourcefeeds/osf_scraper_api/docker-compose.prod.yml dest=/srv/docker-compose.yml

- name: Run docker-compose down
  command: /usr/local/bin/docker-compose -f /srv/docker-compose.yml down

- name: Run docker-compose pull
  command: /usr/local/bin/docker-compose -f /srv/docker-compose.yml pull

- name: delete dangling docker instances
  command: docker rmi $(docker images -f dangling=true -q)
  ignore_errors: True

- name: Run docker-compose up
  command: /usr/local/bin/docker-compose -f /srv/docker-compose.yml up -d

- name: Curl test endpoint
  shell: 'curl -X GET http://{{inventory_hostname}}/api/email/'