---

- hosts: staging-servers
  user: ubuntu
  sudo: True
  roles:
    - role: angstwad.docker_ubuntu

  tasks:

    - name: install common packages
      action: apt pkg={{item}} state=installed
      with_items:
        - python-dev
        - python-setuptools
        - git-core

    - name: install pip
      action: easy_install name=pip

    - name: install virtualenv
      action: pip name={{item.name}} version={{item.version}} executable=/usr/local/bin/pip
      with_items:
        - { name: 'virtualenv', version: '14.0.6' }

    - name: Uninstall docker-py  (https://github.com/docker/docker-py/issues/1395)
      command: pip uninstall -y docker-py
      ignore_errors: True

    - name: Uninstall docker  (https://github.com/docker/docker-py/issues/1395)
      command: pip uninstall -y docker
      ignore_errors: True

    - name: install docker
      command: pip install docker==2.4.2

    - name: install docker-comopse
      command: pip install docker-compose==1.14.0

    - name: add ubuntu to docker gorup
      user: name=ubuntu groups=docker append=yes
