  version: '3'
  services:
    osf_scraper_api:
      image: 'mfowler/local_osf_scraper_api'
      ports:
        - '80:80'
        - '443:443'
      links:
        - selenium
        - redis
      environment:
        - OSF_QUEUE=osf0
        - NUM_RQ_WORKERS=2
      volumes:
        - "~/Desktop/osf/data:/srv/fs"
    redis:
      image: redis
      ports:
        - "6379"
      volumes:
        - "~/Desktop/osf/redis:/data"
    selenium:
      image: selenium/standalone-chrome
      ports:
        - "4444:4444"
      volumes:
        - "/dev/shm:/dev/shm"
    osf_cron:
      image: 'mfowler/local_osf_cron'
      environment:
        - API_DOMAIN=osf_scraper_api:80
      links:
        - osf_scraper_api

